extracts:
  # will extract as env vars if there's no file
  - path: "secret"
  - path: "database.password"
    output_file: "db_password.txt"
  # extract single env var
  - path: "api.key"
    env_var: "API_KEY"
