source_file: "secrets.yaml"
extracts:
  - path: "secret"
  - path: "database.password"
    output_file: "db_password.txt"
    file_mode: "0500"
    env_var: "DB_PASSWORD"
  - path: "api.key"
    output_file: "api_key.txt"
    file_mode: "0400"
    env_var: "API_KEY"
